name: 'Publish package to NPM'
description: 'Publish package to NPM'
author: '@srclaunch'

inputs:
  npm_token:
    description: NPM token for publishing package
    required: true

runs:
  using: 'composite'
  steps:
    - name: Allow private package registry access
      id: allow-private-package-registry-access
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm_token }}" > ~/.npmrc

    - name: Publish to NPM
      shell: bash
      run: pnpm publish-to-npm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}      
