name: 'Publish package to NPM'
description: 'Publish package to NPM'
author: '@srclaunch'

inputs:
  npm_token:
    description: NPM token for publishing package
    required: true

runs:
  using: 'composite'
  steps:
    - name: Allow private package registry access
      id: allow-private-package-registry-access
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm_token }}" > .npmrc
    
    # - name: Login to NPM
    #   id: login-to-npm
    #   shell: bash
    #   run: |
    #     npm login --registry=https://registry.npmjs.org/ --scope=@srclaunch --always-auth

    - name: Publish to NPM
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        NPM_TOKEN: ${{ inputs.npm_token }}  
      run: pnpm publish-to-npm