name: Release packages

on:
  push:
    branches:
      - main

concurrency:
  group: publish-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest

    steps:
      - name: Setup CI/CD environment
        uses: srclaunch/core/packages/ci-cd/.github/actions/setup@main
        with:
          turbo_team: ${{ secrets.TURBO_TEAM }}
          turbo_token: ${{ secrets.TURBO_TOKEN }}
        
      - name: Deploy
        uses: srclaunch/core/packages/ci-cd/.github/actions/deploy@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_ACCESS_TOKEN }}
          turbo_team: ${{ secrets.TURBO_TEAM }}
          turbo_token: ${{ secrets.TURBO_TOKEN }}
        
    