name: 'Release project'
description: 'Buns release workflow'
author: '@srclaunch'

inputs:
  github_token:
    description: GitHub token for creating release
    required: true
  npm_token:
    description: NPM token for publishing package
    required: true
  turbo_team:
    description: Turbo Team name
  turbo_token:
    description: Turbo Team token

runs:
  using: 'composite'
  steps:
   - name: Env files
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        NPM_TOKEN: ${{ inputs.npm_token }}
        TURBO_TEAM: ${{ inputs.turbo_team }}
        TURBO_TOKEN: ${{ inputs.turbo_token }}
      run: echo "_auth = ${NPM_TOKEN}" > .npmrc 
      shell: bash

    - name: Release
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        NPM_TOKEN: ${{ inputs.npm_token }}
        TURBO_TEAM: ${{ inputs.turbo_team }}
        TURBO_TOKEN: ${{ inputs.turbo_token }}
      run: pnpm release
      shell: bash
