export enum AutoComplete {
  Birthday = 'bday',
  BirthdayDay = 'bday-day',
  BirthdayMonth = 'bday-month',
  BirthdayYear = 'bday-year',
  Country = 'country',
  CountryName = 'country-name',
  CreditCardExpiration = 'cc-exp',
  CreditCardExpirationMonth = 'cc-exp-month',
  CreditCardExpirationYear = 'cc-exp-year',
  CreditCardName = 'cc-name',
  CreditCardNumber = 'cc-number',
  CreditCardSecurityCode = 'cc-csc',
  CreditCardType = 'cc-type',
  CurrentPassword = 'current-password',
  EmailAddress = 'email',
  FamilyName = 'family-name',
  GivenName = 'given-name',
  Language = 'language',
  NewPassword = 'new-password',
  OneTimeCode = 'one-time-code',
  Organization = 'organization',
  PhoneNumber = 'tel',
  PostalCode = 'postal-code',
  Sex = 'sex',
  StreetAddress = 'street-address',
  Username = 'username',
}
