export enum Cursor {
  Auto = 'auto',
  Crosshair = 'crosshair',
  Default = 'default',
  Help = 'help',
  Move = 'move',
  NotAllowed = 'not-allowed',
  Pointer = 'pointer',
  Resize = 'resize',
  ResizeBottom = 'resize-bottom',
  ResizeBottomLeft = 'resize-sw',
  ResizeBottomRight = 'resize-se',
  ResizeLeft = 'resize-left',
  ResizeRight = 'resize-right',
  ResizeTop = 'resize-top',
  ResizeTopLeft = 'resize-nw',
  ResizeTopRight = 'resize-ne',
  Text = 'text',
  Wait = 'wait',
}
