export enum ProjectType {
  APIService = 'api-service',
  CLIApplication = 'cli-application',
  ComponentLibrary = 'component-library',
  CoreAPI = 'core-api',
  DesktopApplication = 'desktop-application',
  FiniteStateMachine = 'finite-state-machine',
  Function = 'function',
  GitHubAction = 'github-action',
  GitHubApp = 'github-app',
  IconLibrary = 'icon-library',
  Library = 'library',
  MachineLearningClassifier = 'machine-learning-classifier',
  MobileApplication = 'mobile-application',
  NodeApplication = 'node-application',
  TaskQueue = 'task-queue',
  ThemeLibrary = 'theme-library',
  UniversalApplication = 'universal-application',
  WebApplication = 'web-application',
  WebHook = 'web-hook',
  WebService = 'web-service',
  WebSocketService = 'web-socket-service',
}
