name: Setup Workflow
description: Setup workflow environment
author: '@srclaunch'

runs:
  using: composite
  outputs:
    branch: ${{ steps.get-branch.outputs.name }}
    version: ${{ steps.get-version.outputs.tag }}
  steps:
    - name: Setup Node.js
      uses: 'srclaunch/core/packages/ci-cd/.github/actions/setup-node@main'

    - name: Setup PNPM
      uses: 'srclaunch/core/packages/ci-cd/.github/actions/setup-pnpm@main'

    - name: Get branch name
      id: get-branch
      run: |
        echo "::set-output name=name::${GITHUB_REF#refs/heads/}"

    - name: Get package.json version
      id: get-version
      run: |
        echo "::set-output name=tag::$(jq -r .version package.json)"
