name: Setup Workflow
description: Setup workflow environment
author: '@srclaunch'

outputs:
  branch:
    description: Branch name
    value: ${{ steps.get-branch.outputs.name }}
  version:
    description: Version
    value: ${{ steps.get-version.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get branch name
      id: get-branch
      run: echo "::set-output name=name::${GITHUB_REF#refs/heads/}"
      shell: bash

    - name: Get package.json version
      id: get-version
      run: echo "::set-output name=tag::$(jq -r .version package.json)"
      shell: bash

    - name: Setup PNPM
      uses: 'srclaunch/core/packages/ci-cd/.github/actions/setup-pnpm@main'

    - name: Setup Node.js
      uses: 'srclaunch/core/packages/ci-cd/.github/actions/setup-node@main'

    - name: Install dependencies
      run: pnpm install
      shell: bash
