"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
exports.__esModule = true;
exports.License = exports.TimezoneOffset = exports.TimezoneRegions = exports.SubRegion = exports.Region = exports.LocaleCode = exports.CountryCode = exports.Countries = exports.LanguageCode = exports.CurrencyCode = exports.Currencies = exports.CryptoCurrency = exports.RepositoryEvent = exports.ProjectEvent = exports.ChangesetEvent = exports.RetryStrategy = exports.EnvironmentType = exports.Environments = exports.StaticTyping = exports.CodeLinter = exports.CodeFormatter = exports.InfrastuctureClass = exports.CloudProviders = exports.DeploymentStrategy = exports.Primitives = exports.ModelType = exports.DefaultValue = exports.DataPointMetric = exports.CommunicationMedium = exports.ChatMessageType = exports.ChatMessageStatus = exports.ChatMessageReactionType = exports.ChatMessageAttachmentType = exports.ChangeType = exports.SubscriptionStatus = exports.SubscriptionPlanDuration = exports.PaymentIntentStatus = exports.BuildTool = exports.BuildTarget = exports.BuildPlatform = exports.BuildFormat = exports.PageLeaveMethod = exports.Analytics = exports.Activities = exports.GitHubRunnerOS = exports.GitHubActions = exports.GitHubAction = exports.ActionType = exports.ActionStatus = exports.Action = void 0;
exports.Task = exports.Workflow = exports.GitHubWorkflow = exports.UserRole = exports.UserVerificationStatus = exports.NotificationType = exports.ModalType = exports.TestTool = exports.TestReporter = exports.Runner = exports.RouteRole = exports.PublishAccess = exports.Status = exports.ProjectType = exports.ProblemType = exports.ProblemSeverity = exports.UniversalPackage = exports.TypesPackage = exports.PackageType = exports.PackageManager = exports.NodePackage = exports.BrowserPackage = exports.OnboardingStatus = exports.HttpResponseCode = exports.HttpRequestMethod = exports.LogLevel = void 0;
var action_1 = require("./action");
__createBinding(exports, action_1, "Action");
__createBinding(exports, action_1, "ActionStatus");
__createBinding(exports, action_1, "ActionType");
var github_1 = require("./action/github");
__createBinding(exports, github_1, "GitHubAction");
__createBinding(exports, github_1, "GitHubActions");
__createBinding(exports, github_1, "GitHubRunnerOS");
var index_1 = require("./activity/index");
__createBinding(exports, index_1, "Activities");
var index_2 = require("./analytics/index");
__createBinding(exports, index_2, "Analytics");
var index_3 = require("./analytics/web/index");
__createBinding(exports, index_3, "PageLeaveMethod");
var build_1 = require("./build");
__createBinding(exports, build_1, "BuildFormat");
__createBinding(exports, build_1, "BuildPlatform");
__createBinding(exports, build_1, "BuildTarget");
__createBinding(exports, build_1, "BuildTool");
var index_4 = require("./business/commerce/payment-method/index");
__createBinding(exports, index_4, "PaymentIntentStatus");
var index_5 = require("./business/commerce/subscription/index");
__createBinding(exports, index_5, "SubscriptionPlanDuration");
__createBinding(exports, index_5, "SubscriptionStatus");
var changeset_1 = require("./changeset");
__createBinding(exports, changeset_1, "ChangeType");
var chat_1 = require("./communications/chat");
__createBinding(exports, chat_1, "ChatMessageAttachmentType");
__createBinding(exports, chat_1, "ChatMessageReactionType");
__createBinding(exports, chat_1, "ChatMessageStatus");
__createBinding(exports, chat_1, "ChatMessageType");
var medium_1 = require("./communications/medium");
__createBinding(exports, medium_1, "CommunicationMedium");
__exportStar(require("./condition"), exports);
var index_6 = require("./data/data-point/index");
__createBinding(exports, index_6, "DataPointMetric");
var defaults_1 = require("./data/model/defaults");
__createBinding(exports, defaults_1, "DefaultValue");
var index_7 = require("./data/model/index");
__createBinding(exports, index_7, "ModelType");
var index_8 = require("./data/primitive/index");
__createBinding(exports, index_8, "Primitives");
var deployment_1 = require("./deployment");
__createBinding(exports, deployment_1, "DeploymentStrategy");
var infrastructure_1 = require("./deployment/infrastructure");
__createBinding(exports, infrastructure_1, "CloudProviders");
__createBinding(exports, infrastructure_1, "InfrastuctureClass");
var development_1 = require("./development");
__createBinding(exports, development_1, "CodeFormatter");
__createBinding(exports, development_1, "CodeLinter");
__createBinding(exports, development_1, "StaticTyping");
var environment_1 = require("./environment");
__createBinding(exports, environment_1, "Environments");
__createBinding(exports, environment_1, "EnvironmentType");
var remediation_1 = require("./error/exception/remediation");
__createBinding(exports, remediation_1, "RetryStrategy");
var changeset_2 = require("./event/changeset");
__createBinding(exports, changeset_2, "ChangesetEvent");
var project_1 = require("./event/project");
__createBinding(exports, project_1, "ProjectEvent");
var repository_1 = require("./event/repository");
__createBinding(exports, repository_1, "RepositoryEvent");
var index_9 = require("./i18n/currency/index");
__createBinding(exports, index_9, "CryptoCurrency");
__createBinding(exports, index_9, "Currencies");
__createBinding(exports, index_9, "CurrencyCode");
var index_10 = require("./i18n/language/index");
__createBinding(exports, index_10, "LanguageCode");
var countries_1 = require("./i18n/locale/countries");
__createBinding(exports, countries_1, "Countries");
var country_1 = require("./i18n/locale/country");
__createBinding(exports, country_1, "CountryCode");
var index_11 = require("./i18n/locale/index");
__createBinding(exports, index_11, "LocaleCode");
__exportStar(require("./i18n/locale/locales"), exports);
var region_1 = require("./i18n/locale/region");
__createBinding(exports, region_1, "Region");
__createBinding(exports, region_1, "SubRegion");
var region_2 = require("./i18n/time/region");
__createBinding(exports, region_2, "TimezoneRegions");
__exportStar(require("./i18n/time/regions"), exports);
var timezone_1 = require("./i18n/time/timezone");
__createBinding(exports, timezone_1, "TimezoneOffset");
__exportStar(require("./i18n/time/timezones"), exports);
var license_1 = require("./legal/license");
__createBinding(exports, license_1, "License");
var level_1 = require("./logging/level");
__createBinding(exports, level_1, "LogLevel");
var index_12 = require("./networking/http/index");
__createBinding(exports, index_12, "HttpRequestMethod");
__createBinding(exports, index_12, "HttpResponseCode");
var index_13 = require("./onboarding/index");
__createBinding(exports, index_13, "OnboardingStatus");
var package_1 = require("./package");
__createBinding(exports, package_1, "BrowserPackage");
__createBinding(exports, package_1, "NodePackage");
__createBinding(exports, package_1, "PackageManager");
__createBinding(exports, package_1, "PackageType");
__createBinding(exports, package_1, "TypesPackage");
__createBinding(exports, package_1, "UniversalPackage");
var problem_1 = require("./problem");
__createBinding(exports, problem_1, "ProblemSeverity");
__createBinding(exports, problem_1, "ProblemType");
var project_2 = require("./project");
__createBinding(exports, project_2, "ProjectType");
var queue_1 = require("./queue");
__createBinding(exports, queue_1, "Status");
var release_1 = require("./release");
__createBinding(exports, release_1, "PublishAccess");
var routing_1 = require("./routing");
__createBinding(exports, routing_1, "RouteRole");
var run_1 = require("./run");
__createBinding(exports, run_1, "Runner");
var test_1 = require("./test");
__createBinding(exports, test_1, "TestReporter");
__createBinding(exports, test_1, "TestTool");
var modal_1 = require("./ui/modal");
__createBinding(exports, modal_1, "ModalType");
var notification_1 = require("./ui/notification");
__createBinding(exports, notification_1, "NotificationType");
var verification_1 = require("./user/authentication/verification");
__createBinding(exports, verification_1, "UserVerificationStatus");
var role_1 = require("./user/role");
__createBinding(exports, role_1, "UserRole");
var github_2 = require("./workflow/github");
__createBinding(exports, github_2, "GitHubWorkflow");
var index_14 = require("./workflow/index");
__createBinding(exports, index_14, "Workflow");
var task_1 = require("./workflow/task");
__createBinding(exports, task_1, "Task");
// export function getTypeFromPrimitive(primitive: Primitive) {
//   switch (primitive) {
//     case Primitive.Boolean:
//       return 'boolean';
//     case Primitive.Number:
//       return 'number';
// }
