"use strict";
exports.__esModule = true;
exports.PackageManager = exports.PackageType = exports.TypesPackage = exports.UniversalPackage = exports.NodePackage = exports.BrowserPackage = void 0;
var BrowserPackage;
(function (BrowserPackage) {
    BrowserPackage["AmazonCognitoIdentityJS"] = "amazon-cognito-identity-js";
    BrowserPackage["JSFileDownload"] = "js-file-download";
    BrowserPackage["History"] = "history";
    BrowserPackage["React"] = "react";
    BrowserPackage["ReactColorful"] = "react-colorful";
    BrowserPackage["ReactCountryFlag"] = "react-country-flag";
    BrowserPackage["ReactDOM"] = "react-dom";
    BrowserPackage["ReactDatePicker"] = "react-date-picker";
    BrowserPackage["ReactDropzone"] = "react-dropzone";
    BrowserPackage["ReactSyntaxHighlighter"] = "react-syntax-highlighter";
    BrowserPackage["ReactRedux"] = "react-redux";
    BrowserPackage["ReactRouter"] = "react-router";
    BrowserPackage["SrcLaunchIcons"] = "@srclaunch/icons";
    BrowserPackage["SrcLaunchReactHooks"] = "@srclaunch/react-hooks";
    BrowserPackage["SrcLaunchThemes"] = "@srclaunch/themes";
    BrowserPackage["SrcLaunchWebApplicationState"] = "@srclaunch/web-application-state";
    BrowserPackage["SrcLaunchWebEnvironment"] = "@srclaunch/web-environment";
    BrowserPackage["StyledComponents"] = "styled-components";
})(BrowserPackage = exports.BrowserPackage || (exports.BrowserPackage = {}));
var NodePackage;
(function (NodePackage) {
    NodePackage["AsyncExitHook"] = "async-exit-hook";
    NodePackage["AwsSDK"] = "aws-sdk";
    NodePackage["Compression"] = "compression";
    NodePackage["CORS"] = "cors";
    NodePackage["Config"] = "config";
    NodePackage["Express"] = "express";
    NodePackage["FSExtra"] = "fs-extra";
    NodePackage["Keygrip"] = "keygrip";
    NodePackage["Multer"] = "multer";
    NodePackage["Plaid"] = "plaid";
    NodePackage["Sequelize"] = "sequelize";
    NodePackage["SrcLaunchDataClient"] = "@srclaunch/data-client";
    NodePackage["SrcLaunchHttpServer"] = "@srclaunch/http-server";
    NodePackage["SrcLaunchNodeEnvironment"] = "@srclaunch/node-environment";
})(NodePackage = exports.NodePackage || (exports.NodePackage = {}));
var UniversalPackage;
(function (UniversalPackage) {
    UniversalPackage["Axios"] = "axios";
    UniversalPackage["ChangeCase"] = "change-case";
    UniversalPackage["ColorNamer"] = "color-namer";
    UniversalPackage["CurrencyCodes"] = "currency-codes";
    UniversalPackage["CryptoJS"] = "crypto-js";
    UniversalPackage["EmailValidator"] = "email-validator";
    UniversalPackage["HexRGB"] = "hex-rgb";
    UniversalPackage["JSYaml"] = "js-yaml";
    UniversalPackage["Luxon"] = "luxon";
    UniversalPackage["NanoID"] = "nanoid";
    UniversalPackage["PasswordValidator"] = "password-validator";
    UniversalPackage["PicoColors"] = "pico-colors";
    UniversalPackage["Pluralize"] = "pluralize";
    UniversalPackage["QueryString"] = "query-string";
    UniversalPackage["RGBHex"] = "rgb-hex";
    UniversalPackage["Redux"] = "redux";
    UniversalPackage["ReduxToolkit"] = "@reduxjs/toolkit";
    UniversalPackage["SerializeError"] = "serialize-error";
    UniversalPackage["SrcLaunchActions"] = "@srclaunch/actions";
    UniversalPackage["SrcLaunchA11y"] = "@srclaunch/a11y";
    UniversalPackage["SrcLaunchAuthentication"] = "@srclaunch/authentication";
    UniversalPackage["SrcLaunchExceptions"] = "@srclaunch/exceptions";
    UniversalPackage["SrcLaunchHttpClient"] = "@srclaunch/http-client";
    UniversalPackage["SrcLaunchI18n"] = "@srclaunch/i18n";
    UniversalPackage["SrcLaunchLogger"] = "@srclaunch/logger";
    UniversalPackage["SrcLaunchTransform"] = "@srclaunch/transform";
    UniversalPackage["SrcLaunchValidation"] = "@srclaunch/validation";
    UniversalPackage["Uuid"] = "uuid";
    UniversalPackage["Zxcvbn"] = "zxcvbn";
})(UniversalPackage = exports.UniversalPackage || (exports.UniversalPackage = {}));
var TypesPackage;
(function (TypesPackage) {
    TypesPackage["React"] = "@types/react";
})(TypesPackage = exports.TypesPackage || (exports.TypesPackage = {}));
var PackageType;
(function (PackageType) {
    PackageType["CommonJS"] = "commonjs";
    PackageType["Module"] = "module";
})(PackageType = exports.PackageType || (exports.PackageType = {}));
var PackageManager;
(function (PackageManager) {
    PackageManager["NPM"] = "npm";
    PackageManager["PNPM"] = "pnpm";
    PackageManager["Yarn"] = "yarn";
})(PackageManager = exports.PackageManager || (exports.PackageManager = {}));
