#!/bin/zsh

cd ../packages/a11y && rm -fr .git
cd ../cli && rm -fr .git
cd ../core-api-server && rm -fr .git
cd ../cx && rm -fr .git
cd ../data-client && rm -fr .git
cd ../deployment && rm -fr .git
cd ../dx && rm -fr .git
cd ../exceptions && rm -fr .git
cd ../http-client && rm -fr .git
cd ../http-server && rm -fr .git
cd ../i18n && rm -fr .git
cd ../icons && rm -fr .git
cd ../knowledge && rm -fr .git
cd ../logger && rm -fr .git
cd ../logic && rm -fr .git
cd ../migrate-db && rm -fr .git
cd ../node-environment && rm -fr .git
cd ../pipelines && rm -fr .git
cd ../queues && rm -fr .git
cd ../react-hooks && rm -fr .git
cd ../secrets && rm -fr .git
cd ../themes && rm -fr .git
cd ../types && rm -fr .git
cd ../ui && rm -fr .git
cd ../validation && rm -fr .git
cd ../vs-code-extension && rm -fr .git
cd ../web-application-state && rm -fr .git
cd ../web-environment && rm -fr .git