import {
  BuildFormat,
  BuildPlatform,
  BuildTarget,
  BuildTool,
  CodeFormatter,
  CodeLinter,
  StaticTyping,
  License,
  ComponentLibraryConfig,
  ProjectType,
  PublishAccess,
  TestReporter,
  TestTool,
  UniversalPackage,
  BrowserPackage,
  Environments,
  Runner,
} from '@srclaunch/types';

export default <ComponentLibraryConfig>{
  name: '@srclaunch/ui',
  description: 'SrcLaunch UI React component library',
  type: ProjectType.ComponentLibrary,
  build: [
    {
      bundle: {
        exclude: [
          'react',
          'react-dom',
          'react-dom/client',
          'redux',
          'react-redux',
          'react-router',
          'react-router-dom',
          'styled-components',
        ],
        globals: {
          // react: 'React',
          'styled-components': 'styled',
        },
      },
      formats: [BuildFormat.ESM, BuildFormat.UMD],
      input: {
        directory: 'src',
        file: 'index.tsx',
      },
      library: true,
      platform: BuildPlatform.Browser,
      react: true,
      target: BuildTarget.Modules,
      tool: BuildTool.Vite,
      types: true,
    },
    {
      bundle: {
        exclude: [
          'react',
          'react-dom',
          'react-dom/client',
          'redux',
          'react-redux',
          'react-router',
          'react-router-dom',
          'styled-components',
        ],
        globals: {
          // react: 'React',
          'styled-components': 'styled',
        },
      },
      formats: [BuildFormat.ESM, BuildFormat.UMD],
      input: {
        directory: 'src/__docs__',
        file: 'index.html',
      },
      output: {
        directory: 'docs',
      },
      platform: BuildPlatform.Browser,
      react: true,
      target: BuildTarget.Modules,
      tool: BuildTool.Vite,
      types: false,
    },
  ],
  test: {
    coverage: {
      reporters: [TestReporter.Lcov, TestReporter.JSONSummary],
    },
    tool: TestTool.Jest,
  },
  environments: {
    development: {
      formatters: [CodeFormatter.Prettier],
      linters: [CodeLinter.ESLint, CodeLinter.Stylelint],
      staticTyping: [StaticTyping.TypeScript],
    },
  },
  release: {
    deployment: {
      githubPages: true,
    },
    publish: {
      access: PublishAccess.Public,
      license: License.MIT,
      registry: 'https://registry.npmjs.org/',
    },
  },
  requirements: {
    node: '>=16',
    packages: [
      BrowserPackage.AmazonCognitoIdentityJS,
      BrowserPackage.History,
      BrowserPackage.React,
      BrowserPackage.ReactDOM,
      BrowserPackage.ReactColorful,
      BrowserPackage.ReactCountryFlag,
      BrowserPackage.ReactDropzone,
      BrowserPackage.ReactSyntaxHighlighter,
      BrowserPackage.SrcLaunchIcons,
      BrowserPackage.SrcLaunchReactHooks,
      BrowserPackage.SrcLaunchThemes,
      BrowserPackage.SrcLaunchWebApplicationState,
      BrowserPackage.SrcLaunchWebEnvironment,
      BrowserPackage.StyledComponents,
      UniversalPackage.ColorNamer,
      UniversalPackage.CryptoJS,
      UniversalPackage.HexRGB,
      UniversalPackage.Luxon,
      UniversalPackage.NanoID,
      UniversalPackage.QueryString,
      UniversalPackage.RGBHex,
      UniversalPackage.SrcLaunchExceptions,
      UniversalPackage.SrcLaunchHttpClient,
      UniversalPackage.SrcLaunchI18n,
      UniversalPackage.SrcLaunchLogger,
      UniversalPackage.SrcLaunchTransform,
      UniversalPackage.SrcLaunchValidation,
    ],
    peerPackages: [
      BrowserPackage.ReactRedux,
      BrowserPackage.ReactRouter,
      UniversalPackage.Redux,
      UniversalPackage.ReduxToolkit,
    ],
    srclaunch: {
      dx: true,
      cli: true,
      types: true,
    },
  },
  run: {
    [Environments.Development]: {
      react: true,
      input: {
        directory: 'src/__docs__',
      },
      runner: Runner.Vite,
      styledComponents: true,
    },
  },
};
