export enum BorderColor {
  Black = 'var(--color-black-rgb)',
  BlackContrast = 'var(--color-black-contrast-rgb)',
  Dark = 'var(--border-color-dark-rgb)',
  Darker = 'var(--border-color-darker-rgb)',
  Darkest = 'var(--border-color-darkest-rgb)',
  Default = 'var(--border-color-default-rgb)',
  Error = 'var(--color-error-rgb)',
  ErrorContrast = 'var(--color-error-contrast-rgb)',
  Info = 'var(--color-info-rgb)',
  InfoContrast = 'var(--color-info-contrast-rgb)',
  Inherit = 'inherit',
  InputControl = 'var(--border-color-input-control-rgb)',
  Light = 'var(--border-color-light-rgb)',
  Lighter = 'var(--border-color-lighter-rgb)',
  Lightest = 'var(--border-color-lightest-rgb)',
  Primary = 'var(--color-primary-rgb)',
  PrimaryContrast = 'var(--color-primary-contrast-rgb)',
  Secondary = 'var(--color-secondary-rgb)',
  SecondaryContrast = 'var(--color-secondary-contrast-rgb)',
  Success = 'var(--color-success-rgb)',
  SuccessContrast = 'var(--color-success-contrast-rgb)',
  Transparent = 'transparent',
  Warning = 'var(--color-warning-rgb)',
  WarningContrast = 'var(--color-warning-contrast-rgb)',
  White = 'var(--color-white-rgb)',
  WhiteContrast = 'var(--color-white-contrast-rgb)',
}
