"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.PassportNumberCondition = exports.EmailAddressCondition = exports.CreditCardCondition = exports.NumberCondition = exports.IntegerCondition = exports.FloatCondition = exports.URLCondition = exports.SlugCondition = exports.PortCondition = exports.MimeTypeCondition = exports.MagnetURICondition = exports.MACAddressCondition = exports.IPAddressRangeCondition = exports.IPAddressCondition = exports.EmailCondition = exports.DomainNameCondition = exports.DataURICondition = exports.TagsCondition = exports.MenuCondition = exports.StreetAddressCondition = exports.StateCondition = exports.ProvinceCondition = exports.PostalCodeCondition = exports.LongitudeCondition = exports.LatitudeCondition = exports.CountryCondition = exports.CityCondition = exports.LanguageCondition = exports.EthereumAddressCondition = exports.CurrencyCondition = exports.BitcoinAddressCondition = exports.MarkdownCondition = exports.JSONCondition = exports.HexadecimalCondition = exports.YearCondition = exports.WeekdayCondition = exports.TimeRangeCondition = exports.TimeOfDayCondition = exports.TimeCondition = exports.MonthCondition = exports.DayOfMonthCondition = exports.DateTimeCondition = exports.DateRangeCondition = exports.DateCondition = exports.BooleanCondition = exports.UUIDCondition = exports.SemanticVersionCondition = exports.MD5Condition = exports.AlgorithmHashCondition = exports.ColorCondition = void 0;
exports.AuthenticationCondition = exports.Condition = exports.StringCondition = exports.LongTextCondition = exports.VATCondition = exports.TaxIDNumberCondition = exports.ISSNCondition = exports.ISMNCondition = exports.ISINCondition = exports.ISBNCondition = exports.IBANCondition = exports.EINCondition = exports.EANCondition = exports.BICCondition = exports.AirportCondition = exports.SocialSecurityNumberCondition = exports.PhoneNumberCondition = exports.PasswordCondition = void 0;
var color_1 = require("./primitive/appearance/color");
__createBinding(exports, color_1, "ColorCondition");
var application_1 = require("./primitive/application");
__createBinding(exports, application_1, "AlgorithmHashCondition");
__createBinding(exports, application_1, "MD5Condition");
__createBinding(exports, application_1, "SemanticVersionCondition");
__createBinding(exports, application_1, "UUIDCondition");
var boolean_1 = require("./primitive/boolean");
__createBinding(exports, boolean_1, "BooleanCondition");
var date_1 = require("./primitive/date");
__createBinding(exports, date_1, "DateCondition");
__createBinding(exports, date_1, "DateRangeCondition");
__createBinding(exports, date_1, "DateTimeCondition");
__createBinding(exports, date_1, "DayOfMonthCondition");
__createBinding(exports, date_1, "MonthCondition");
__createBinding(exports, date_1, "TimeCondition");
__createBinding(exports, date_1, "TimeOfDayCondition");
__createBinding(exports, date_1, "TimeRangeCondition");
__createBinding(exports, date_1, "WeekdayCondition");
__createBinding(exports, date_1, "YearCondition");
var format_1 = require("./primitive/format");
__createBinding(exports, format_1, "HexadecimalCondition");
__createBinding(exports, format_1, "JSONCondition");
__createBinding(exports, format_1, "MarkdownCondition");
var currency_1 = require("./primitive/i18n/currency");
__createBinding(exports, currency_1, "BitcoinAddressCondition");
__createBinding(exports, currency_1, "CurrencyCondition");
__createBinding(exports, currency_1, "EthereumAddressCondition");
var language_1 = require("./primitive/i18n/language");
__createBinding(exports, language_1, "LanguageCondition");
var locale_1 = require("./primitive/i18n/locale");
__createBinding(exports, locale_1, "CityCondition");
__createBinding(exports, locale_1, "CountryCondition");
__createBinding(exports, locale_1, "LatitudeCondition");
__createBinding(exports, locale_1, "LongitudeCondition");
__createBinding(exports, locale_1, "PostalCodeCondition");
__createBinding(exports, locale_1, "ProvinceCondition");
__createBinding(exports, locale_1, "StateCondition");
__createBinding(exports, locale_1, "StreetAddressCondition");
var menu_1 = require("./primitive/menu");
__createBinding(exports, menu_1, "MenuCondition");
__createBinding(exports, menu_1, "TagsCondition");
var network_1 = require("./primitive/network");
__createBinding(exports, network_1, "DataURICondition");
__createBinding(exports, network_1, "DomainNameCondition");
__createBinding(exports, network_1, "EmailCondition");
__createBinding(exports, network_1, "IPAddressCondition");
__createBinding(exports, network_1, "IPAddressRangeCondition");
__createBinding(exports, network_1, "MACAddressCondition");
__createBinding(exports, network_1, "MagnetURICondition");
__createBinding(exports, network_1, "MimeTypeCondition");
__createBinding(exports, network_1, "PortCondition");
__createBinding(exports, network_1, "SlugCondition");
__createBinding(exports, network_1, "URLCondition");
var number_1 = require("./primitive/number");
__createBinding(exports, number_1, "FloatCondition");
__createBinding(exports, number_1, "IntegerCondition");
__createBinding(exports, number_1, "NumberCondition");
var pii_1 = require("./primitive/pii");
__createBinding(exports, pii_1, "CreditCardCondition");
__createBinding(exports, pii_1, "EmailAddressCondition");
__createBinding(exports, pii_1, "PassportNumberCondition");
__createBinding(exports, pii_1, "PasswordCondition");
__createBinding(exports, pii_1, "PhoneNumberCondition");
__createBinding(exports, pii_1, "SocialSecurityNumberCondition");
var airport_1 = require("./primitive/places/transportation/airport");
__createBinding(exports, airport_1, "AirportCondition");
var standards_1 = require("./primitive/standards");
__createBinding(exports, standards_1, "BICCondition");
__createBinding(exports, standards_1, "EANCondition");
__createBinding(exports, standards_1, "EINCondition");
__createBinding(exports, standards_1, "IBANCondition");
__createBinding(exports, standards_1, "ISBNCondition");
__createBinding(exports, standards_1, "ISINCondition");
__createBinding(exports, standards_1, "ISMNCondition");
__createBinding(exports, standards_1, "ISSNCondition");
__createBinding(exports, standards_1, "TaxIDNumberCondition");
__createBinding(exports, standards_1, "VATCondition");
var string_1 = require("./primitive/string");
__createBinding(exports, string_1, "LongTextCondition");
__createBinding(exports, string_1, "StringCondition");
var Condition;
(function (Condition) {
    Condition["Contains"] = "contains";
    Condition["HasCharacterCount"] = "has-character-count";
    Condition["HasNumberCount"] = "has-number-count";
    Condition["HasLetterCount"] = "has-letter-count";
    Condition["HasLowercaseCount"] = "has-lowercase-count";
    Condition["HasSpacesCount"] = "has-spaces-count";
    Condition["HasSymbolCount"] = "has-symbol-count";
    Condition["HasUppercaseCount"] = "has-uppercase-count";
    Condition["IsAfter"] = "is-after";
    Condition["IsAfterOrEqual"] = "is-after-or-equal";
    Condition["IsAirport"] = "is-airport";
    Condition["IsAlpha"] = "is-alpha";
    Condition["IsAlphanumeric"] = "is-alphanumeric";
    Condition["IsAlgorithmHash"] = "is-algorithm-hash";
    Condition["IsAscii"] = "is-ascii";
    Condition["IsBase64"] = "is-base-64";
    Condition["IsBefore"] = "is-before";
    Condition["IsBeforeOrAfter"] = "is-before-or-after";
    Condition["IsBeforeOrEqual"] = "is-before-or-equal";
    Condition["IsBetween"] = "is-between";
    Condition["IsBIC"] = "is-bic";
    Condition["IsBitcoinAddress"] = "is-bitcoin-address";
    Condition["IsBoolean"] = "is-boolean";
    Condition["IsColor"] = "is-color";
    Condition["IsComplexEnough"] = "is-complex-enough";
    Condition["IsCountry"] = "is-country";
    Condition["IsCreditCard"] = "is-credit-card";
    Condition["IsCurrency"] = "is-currency";
    Condition["IsDataURI"] = "is-data-uri";
    Condition["IsDate"] = "is-date";
    Condition["IsDateRange"] = "is-date-range";
    Condition["IsDateTime"] = "is-date-time";
    Condition["IsDayOfMonth"] = "is-day-of-month";
    Condition["IsDecimal"] = "is-decimal";
    Condition["IsDivisibleBy"] = "is-divisible-by";
    Condition["IsDomainName"] = "is-domain-name";
    Condition["IsEmailAddress"] = "is-email-address";
    Condition["IsEthereumAddress"] = "is-ethereum-address";
    Condition["IsEAN"] = "is-ean";
    Condition["IsEIN"] = "is-ein";
    Condition["IsEqual"] = "is-equal";
    Condition["IsEvenNumber"] = "is-even-number";
    Condition["IsFloat"] = "is-float";
    Condition["IsIBAN"] = "is-iban";
    Condition["IsGreaterThan"] = "greater-than";
    Condition["IsGreaterThanOrEqual"] = "greater-than-or-equal";
    Condition["IsHSLColor"] = "is-hsl-color";
    Condition["IsHexColor"] = "is-hex-color";
    Condition["IsHexadecimal"] = "is-hexadecimal";
    Condition["IsIdentityCardCode"] = "is-identity-card-code";
    Condition["IsIMEI"] = "is-imei";
    Condition["IsInIPAddressRange"] = "is-in-ip-address-range";
    Condition["IsInList"] = "is-in-list";
    Condition["IsInTheLast"] = "is-in-the-last";
    Condition["IsInteger"] = "is-integer";
    Condition["IsIPAddress"] = "is-ip-address";
    Condition["IsIPAddressRange"] = "is-ip-address-range";
    Condition["IsISBN"] = "is-isbn";
    Condition["IsISIN"] = "is-isin";
    Condition["IsISMN"] = "is-ismn";
    Condition["IsISRC"] = "is-isrc";
    Condition["IsISSN"] = "is-issn";
    Condition["IsISO4217"] = "is-iso-4217";
    Condition["IsISO8601"] = "is-iso-8601";
    Condition["IsISO31661Alpha2"] = "is-iso-31661-alpha-2";
    Condition["IsISO31661Alpha3"] = "is-iso-31661-alpha-3";
    Condition["IsJSON"] = "is-json";
    Condition["IsLanguage"] = "is-language";
    Condition["IsLatitude"] = "is-latitude";
    Condition["IsLongitude"] = "is-longitude";
    Condition["IsLengthEqual"] = "is-length-equal";
    Condition["IsLengthGreaterThan"] = "is-length-greater-than";
    Condition["IsLengthGreaterThanOrEqual"] = "is-length-great-than-or-equal";
    Condition["IsLengthLessThan"] = "is-length-less-than";
    Condition["IsLengthLessThanOrEqual"] = "is-length-less-than-or-equal";
    Condition["IsLessThan"] = "less-than";
    Condition["IsLessThanOrEqual"] = "less-than-or-equal";
    Condition["IsLicensePlateNumber"] = "is-license-plate-number";
    Condition["IsLowercase"] = "is-lowercase";
    Condition["IsOctal"] = "is-octal";
    Condition["IsMACAddress"] = "is-mac-address";
    Condition["IsMD5"] = "is-md5";
    Condition["IsMagnetURI"] = "is-magnet-uri";
    Condition["IsMarkdown"] = "is-markdown";
    Condition["IsMimeType"] = "is-mime-type";
    Condition["IsMonth"] = "is-month";
    Condition["IsNegativeNumber"] = "is-negative-number";
    Condition["IsNotDate"] = "is-not-date";
    Condition["IsNotEqual"] = "is-not-equal";
    Condition["IsNotInIPAddressRange"] = "is-not-in-ip-address-range";
    Condition["IsNotInList"] = "is-not-in-list";
    Condition["IsNotNull"] = "is-not-null";
    Condition["IsNotRegexMatch"] = "is-not-regex-match";
    Condition["IsNotToday"] = "is-not-today";
    Condition["IsNumber"] = "is-number";
    Condition["IsNumeric"] = "is-numeric";
    Condition["IsOddNumber"] = "is-odd-number";
    Condition["IsPassportNumber"] = "is-passport-number";
    Condition["IsPhoneNumber"] = "is-phone-number";
    Condition["IsPort"] = "is-port";
    Condition["IsPositiveNumber"] = "is-positive-number";
    Condition["IsPostalCode"] = "is-postal-code";
    Condition["IsProvince"] = "is-province";
    Condition["IsRGBColor"] = "is-rgb-color";
    Condition["IsRegexMatch"] = "is-regex-match";
    Condition["IsRequired"] = "is-required";
    Condition["IsSemanticVersion"] = "is-semantic-version";
    Condition["IsSlug"] = "is-slug";
    Condition["IsSSN"] = "is-ssn";
    Condition["IsState"] = "is-state";
    Condition["IsStreetAddress"] = "is-street-address";
    Condition["IsString"] = "is-string";
    Condition["IsStrongPassword"] = "is-strong-password";
    Condition["IsTags"] = "is-tags";
    Condition["IsTaxIDNumber"] = "is-tax-id-number";
    Condition["IsThisMonth"] = "is-this-month";
    Condition["IsThisQuarter"] = "is-this-quarter";
    Condition["IsThisWeek"] = "is-this-week";
    Condition["IsThisWeekend"] = "is-this-weekend";
    Condition["IsThisYear"] = "is-this-year";
    Condition["IsTime"] = "is-time";
    Condition["IsTimeOfDay"] = "is-time-of-day";
    Condition["IsTimeRange"] = "is-time-range";
    Condition["IsToday"] = "is-today";
    Condition["IsURL"] = "is-url";
    Condition["IsUUID"] = "is-uuid";
    Condition["IsUppercase"] = "is-uppercase";
    Condition["IsUsernameAvailable"] = "is-username-available";
    Condition["IsValidStreetAddress"] = "is-valid-street-address";
    Condition["IsVATIDNumber"] = "is-vat-id-number";
    Condition["IsWeekday"] = "is-weekday";
    Condition["IsWeekend"] = "is-weekend";
    Condition["IsYear"] = "is-year";
})(Condition = exports.Condition || (exports.Condition = {}));
var AuthenticationCondition;
(function (AuthenticationCondition) {
    AuthenticationCondition["IsAuthenticated"] = "is-authenticated";
    AuthenticationCondition["IsNotAuthenticated"] = "is-not-authenticated";
    AuthenticationCondition["IsUsernameAvailable"] = "is-username-available";
    AuthenticationCondition["PasswordMismatch"] = "password-mismatch";
})(AuthenticationCondition = exports.AuthenticationCondition || (exports.AuthenticationCondition = {}));
