export enum RepositoryEvent {
  BranchCreated = 'branch-created',
  BranchDeleted = 'branch-deleted',
  BranchProtectionRuleCreated = 'branch_protection_rule_created',
  BranchProtectionRuleDeleted = 'branch_protection_rule_deleted',
  BranchProtectionRuleUpdated = 'branch_protection_rule_updated',

  CheckRunCompleted = 'check_run_completed',
  CheckRunCreated = 'check_run_created',
  CheckRunRequested = 'check_run_requested',
  CheckRunRerequested = 'check_run_rerequested',
  CheckSuiteCompleted = 'check_suite_completed',

  CommitStatusChanged = 'commit_status_changed',

  DeploymentCreated = 'deployment_created',
  DeploymentStatusUpdated = 'deployment_status_updated',

  DiscussionAnswered = 'discussion_answered',
  DiscussionCategoryChanged = 'discussion_category_changed',
  DiscussionCommentCreated = 'discussion_comment_created',
  DiscussionCommentEdited = 'discussion_comment_edited',
  DiscussionCommentDeleted = 'discussion_comment_deleted',
  DiscussionCreated = 'discussion_created',
  DiscussionDeleted = 'discussion_deleted',
  DiscussionLabeled = 'discussion_labeled',
  DiscussionLocked = 'discussion_locked',
  DiscussionPinned = 'discussion_pinned',
  DiscussionTransferred = 'discussion_transferred',
  DiscussionEdited = 'discussion_edited',
  DiscussionUnanswered = 'discussion_unanswered',
  DiscussionUnlabeled = 'discussion_unlabeled',
  DiscussionUnlocked = 'discussion_unlocked',
  DiscussionUnpinned = 'discussion_unpinned',

  Dispatch = 'dispatch',

  Forked = 'forked',

  IssueCommentCreated = 'issue_comment_created',
  IssueCommentDeleted = 'issue_comment_deleted',
  IssueCommentEdited = 'issue_comment_edited',

  IssueAssigned = 'issue_assigned',
  IssueClosed = 'issue_closed',
  IssueDeleted = 'issue_deleted',
  IssueDemilestoned = 'issue_demilestoned',
  IssueEdited = 'issue_edited',
  IssueLabeled = 'issue_labeled',
  IssueLocked = 'issue_locked',
  IssueMilestoned = 'issue_milestoned',
  IssueOpened = 'issue_opened',
  IssuePinned = 'issue_pinned',
  IssueReopened = 'issue_reopened',
  IssueTransferred = 'issue_transferred',
  IssueUnassigned = 'issue_unassigned',
  IssueUnlabeled = 'issue_unlabeled',
  IssueUnlocked = 'issue_unlocked',
  IssueUnpinned = 'issue_unpinned',

  LabelCreated = 'label_created',
  LabelDeleted = 'label_deleted',
  LabelEdited = 'label_edited',

  MilestoneClosed = 'milestone_closed',
  MilestoneCreated = 'milestone_created',
  MilestoneDeleted = 'milestone_deleted',
  MilestoneEdited = 'milestone_edited',
  MilestoneOpened = 'milestone_opened',

  PageBuild = 'page_build',

  ProjectCardCreated = 'project_card_created',
  ProjectCardConvertedToIssue = 'project_card_converted_to_issue',
  ProjectCardDeleted = 'project_card_deleted',
  ProjectCardEdited = 'project_card_edited',
  ProjectCardMoved = 'project_card_moved',

  ProjectColumnCreated = 'project_column_created',
  ProjectColumnDeleted = 'project_column_deleted',
  ProjectColumnMoved = 'project_column_moved',
  ProjectColumnUpdated = 'project_column_updated',

  ProjectClosed = 'project_closed',
  ProjectCreated = 'project_created',
  ProjectDeleted = 'project_deleted',
  ProjectEdited = 'project_edited',
  ProjectReopened = 'project_reopened',

  Public = 'public',

  PullRequestAutoMergeEnabled = 'pull_request_automerge_enabled',
  PullRequestAutoMergeDisabled = 'pull_request_automerge_disabled',
  PullRequestAssigned = 'pull_request_assigned',
  PullRequestUnassigned = 'pull_request_unassigned',
  PullRequestLabeled = 'pull_request_labeled',
  PullRequestUnlabeled = 'pull_request_unlabeled',
  PullRequestOpened = 'pull_request_opened',
  PullRequestEdited = 'pull_request_edited',
  PullRequestClosed = 'pull_request_closed',
  PullRequestReopened = 'pull_request_reopened',
  PullRequestSynchronize = 'pull_request_synchronize',
  PullRequestConvertedToDraft = 'pull_request_converted_to_draft',
  PullRequestReadyForReview = 'pull_request_ready_for_review',
  PullRequestLocked = 'pull_request_locked',
  PullRequestUnlocked = 'pull_request_unlocked',
  PullRequestReviewRequested = 'pull_request_review_requested',
  PullRequestReviewRequestRemoved = 'pull_request_review_request_removed',

  PullRequestCommentCreated = 'pull_request_comment_created',
  PullRequestCommentDeleted = 'pull_request_comment_deleted',
  PullRequestCommentEdited = 'pull_request_comment_edited',

  PullRequestReviewSubmitted = 'pull_request_review_submitted',
  PullRequestReviewDismissed = 'pull_request_review_dismissed',
  PullRequestReviewEdited = 'pull_request_review_edited',

  PullRequestReviewCommentCreated = 'pull_request_review_comment_created',
  PullRequestReviewCommentDeleted = 'pull_request_review_comment_deleted',
  PullRequestReviewCommentEdited = 'pull_request_review_comment_edited',

  PullRequestTargetAutoMergeEnabled = 'pull_request_target_automerge_enabled',
  PullRequestTargetAutoMergeDisabled = 'pull_request_target_automerge_disabled',
  PullRequestTargetAssigned = 'pull_request_target_assigned',
  PullRequestTargetUnassigned = 'pull_request_target_unassigned',
  PullRequestTargetLabeled = 'pull_request_target_labeled',
  PullRequestTargetUnlabeled = 'pull_request_target_unlabeled',
  PullRequestTargetOpened = 'pull_request_target_opened',
  PullRequestTargetEdited = 'pull_request_target_edited',
  PullRequestTargetClosed = 'pull_request_target_closed',
  PullRequestTargetReopened = 'pull_request_target_reopened',
  PullRequestTargetSynchronize = 'pull_request_target_synchronize',
  PullRequestTargetConvertedToDraft = 'pull_request_target_converted_to_draft',
  PullRequestTargetReadyForReview = 'pull_request_target_ready_for_review',
  PullRequestTargetLocked = 'pull_request_target_locked',
  PullRequestTargetUnlocked = 'pull_request_target_unlocked',
  PullRequestTargetReviewRequested = 'pull_request_target_review_requested',
  PullRequestTargetReviewRequestRemoved = 'pull_request_target_review_request_removed',

  Push = 'push',

  RegistryPackagePublished = 'registry_package_published',
  RegistryPackageUpdated = 'registry_package_updated',

  ReleasePublished = 'release_published',
  ReleaseUnpublished = 'release_unpublished',
  ReleaseCreated = 'release_created',
  ReleaseDeleted = 'release_deleted',
  ReleaseEdited = 'release_edited',
  ReleasePrereleased = 'release_prereleased',
  ReleaseReleased = 'release_released',

  Schedule = 'schedule',

  Starred = 'starred',

  TagCreated = 'tag_created',
  TagDeleted = 'tag_deleted',

  WikiPageCreated = 'wiki_page_created',
  WikiPageDeleted = 'wiki_page_deleted',
  WikiPageUpdated = 'wiki_page_updated',

  WorkflowCall = 'workflow_call',

  WorkflowDispatch = 'workflow_dispatch',

  WorkflowRun = 'workflow_run',
}
