name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  publish_package:
    name: Publish package
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup job
        uses: '@srclaunch/workflows/.github/actions/setup@main'

      - name: Build project
        uses: '@srclaunch/workflows/.github/actions/build@main'

      - name: Run tests and collect coverage
        uses: '@srclaunch/workflows/.github/actions/test@main'
        with:
          repository_owner: ${{ github.event.repository.owner.login }}
          repository_name: ${{ github.event.repository.name }}
          branch: ${{ needs.setup.outputs.branch }}

      - name: Publish to NPM
        uses: '@srclaunch/workflows/.github/actions/publish@main'
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
