export enum Color {
  Black = 'var(--color-black)',
  Blue = 'var(--color-blue)',
  Error = 'var(--color-error)',
  Info = 'var(--color-info)',
  Lime = 'var(--color-lime)',
  NearBlack = 'var(--color-near-black)',
  Pink = 'var(--color-pink)',
  Primary = 'var(--color-primary)',
  Secondary = 'var(--color-secondary)',
  Success = 'var(--color-success)',
  Transparent = 'var(--color-transparent)',
  Turquoise = 'var(--color-turquoise)',
  Warning = 'var(--color-warning)',
  White = 'var(--color-white)',
}
