export enum Color {
  Black = 'var(--black-color)',
  Blue = 'var(--blue-color)',
  Error = 'var(--error-color)',
  Info = 'var(--info-color)',
  Lime = 'var(--lime-color)',
  NearBlack = 'var(--near-black-color)',
  Pink = 'var(--pink-color)',
  Primary = 'var(--primary-color)',
  Secondary = 'var(--secondary-color)',
  Success = 'var(--success-color)',
  Transparent = 'var(--transparent-color)',
  Turquoise = 'var(--turquoise-color)',
  Warning = 'var(--warning-color)',
  White = 'var(--white-color)',
}
